export const SEARCH_PARAM_KEYS = {
  NAME: 'name',
  PAGE: 'page',
  QUERY: 'q',
  SORT: 'sort',
  DOCUMENTS: 'documents',
  EMPLOYEES: 'employees',
  FILTER: 'filter',
  EQUIPMENT: 'equipment',
  BENEFIT: 'benefit',
  STATUS: 'status',
  CATEGORY: 'category',
  DICTIONARY: 'dictionary',
  ABSENCES: 'absences',
  TYPE: 'type',
  FROM: 'from',
  TO: 'to',
  YEAR_MONTH: 'yearMonth',
  ITEMS_PER_PAGE: 'perPage',
  START_DATE: 'startDate',
  START_TIME: 'startTime',
  DURATION: 'duration',
  END_DATE: 'endDate',
  DATE: 'date',
  WEEK: 'week',
  STEP: 'step',
  SKILLS: 'skills',
  VALIDATE: 'validate',
  ATTENDANCE: 'attendance',
  PAYROLL: 'payroll',
  TOKEN: 'token',
};

export type SearchParamKey = keyof typeof SEARCH_PARAM_KEYS;
